//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtyEarth
    {
        public int Id { get; set; }
        public int IdIsThereAHouse { get; set; }
        public Nullable<int> IdPhotoAdress { get; set; }
        public int IdClient { get; set; }
        public int SquareEarth { get; set; }
        public int Price { get; set; }
        public string Adress { get; set; }
    
        public virtual AdressPhoto AdressPhoto { get; set; }
        public virtual Client Client { get; set; }
        public virtual IsThereAHouse IsThereAHouse { get; set; }
    }
}
