//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtyFlat
    {
        public int Id { get; set; }
        public int IdDestiny { get; set; }
        public int IdQuantityRoom { get; set; }
        public int IdFloor { get; set; }
        public Nullable<int> IdPhotoAdress { get; set; }
        public int IdClient { get; set; }
        public int SquareFlat { get; set; }
        public int Price { get; set; }
        public string Adress { get; set; }
    
        public virtual AdressPhoto AdressPhoto { get; set; }
        public virtual Client Client { get; set; }
        public virtual Destiny Destiny { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual QuantityRoom QuantityRoom { get; set; }
    }
}
